monitor = DP-1, 2560x1440@60, 0x0, 1, bitdepth, 10, cm, hdr
monitor = HDMI-A-1, disable
monitor = HDMI-A-2, disable

exec-once = @GREETER_COMMAND@

bind = SUPER SHIFT, E, exit
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
}
